### ISSUE TITLE
[ASK] Order Gojek Feature

### ISSUE THREAD

**Issue by dehamzah** [mychaelgo/gojek#1]
Is there will be support for ordering gojek via this API wrapper?

**Comment by mychaelgo** [comment]
@dehamzah yup it's possible, but currently i'm not push the code to github yet

**Comment by dehamzah** [comment]
@mychaelgo can you share the postman collection first?
so me or others can contribute via PR

**Comment by mychaelgo** [comment]
@dehamzah some of the API is broken. Here the postman collection

https://www.getpostman.com/collections/edc1ea330010a06e85df
