### ISSUE TITLE
Publish new code to NPM

### ISSUE THREAD

**Issue by rohmanhm** [mychaelgo/gojek#12]
Version 1.1.0 on NPM still using old code.

Inside the docs, you described we need to passed page and limit parameters to `getGoPayHistory` function.
https://github.com/mychaelgo/gojek/blob/master/README.md#get-go-pay-transaction-history

But, in version 1.1.0 at NPM there are no page and limit parameters. Only callback.
![image](https://user-images.githubusercontent.com/7524911/42612883-00158ece-85c8-11e8-9ede-9f2b4cb96fa6.png)

After looking inside this repo, you have provided the page and limit parameters.
https://github.com/mychaelgo/gojek/blob/906b95f32e5609a56759503125c8960e338c8d61/src/payment.js#L12-L22

I think you just need to publish new code to NPM like version 1.1.1

**Comment by mychaelgo** [comment]
@rohmanhm please check new version
