### ISSUE TITLE
Snif

### ISSUE THREAD

**Issue by lintangtimur** [mychaelgo/gojek#16]
apakah bisa snif apk game?
yang saya lakukan mitm dengan proxy dan bypass cert pinning, tapi hanya work di arsitektur x86,
karena kebanyakan apk game tidak dibuild ke x86

**Comment by mychaelgo** [comment]
@lintangtimur halo, maksudnya minta bantuan untuk snif apk game kah?

**Comment by lintangtimur** [comment]
> @lintangtimur halo, maksudnya minta bantuan untuk snif apk game kah?

iyaa, kalo sniff game gimana ya? Btw, sudah pernah sniff app Dana?

**Comment by mychaelgo** [comment]
@lintangtimur seharusnya sama sih sprti Apps caranya.
Kalau DANA sudah, cuma ribet 😅
