### ISSUE TITLE
Generate Customer Token

### ISSUE THREAD

**Issue by dickyadrian** [mychaelgo/gojek#17]
Hi!
I'm really interested in using this for my project but I couldn't connect it, I'm stuck at generating customer token. 
Are setting Unique ID and appVersion required? Since Gojek always throw error at generating customer token.

Thanks!

**Comment by mychaelgo** [comment]
hello @dickyadrian , i've not look yet again with the new API in gojek app itself. 
They must be updating the flow for authentication that makes generating customer token didn't work as expecter

**Comment by xinweiiiii** [comment]
Hi @dickyadrian by any chance did you manage to generate the customer token? I am facing some error with that APi call as well.

**Comment by evoreign** [comment]
> Hi @dickyadrian by any chance did you manage to generate the customer token? I am facing some error with that APi call as well.

Nah, I'm facing the same problem. and I think the owner would archive this repo sooner or later because it's been 4 years since he push any update.

**Comment by mychaelgo** [comment]
@dickyadrian @xinweiiiii @evoreign 
i'm still in progress to refactor the client because gojek also change the way how user authenticate, right now only some API are available such as generate token & bank accounts in the new version
