### ISSUE TITLE
Not getting token after calling login API

### ISSUE THREAD

**Issue by adhikasp** [mychaelgo/gojek#2]
I got empty body `{}` after calling the login API.

```js
var gojek = require('gojek')
gojek.login('MY_EMAIL , 'MY_PASSWORD function(error, resp    onse, body) {
         console.log(body);
 })
```

Result
```
{}
```

**Comment by mychaelgo** [comment]
@adhikasp hi, the endpoint changed

here sample request

```
curl -X POST \
  https://api.gojekapi.com/v3/customers/login_with_email \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
	"email": "YOUREMAIL"
}'
```

**Comment by mychaelgo** [comment]
@adhikasp hi, you can update npm gojek to version 1.1.0 you can login with function
`gojek.loginWithEmail()` or `gojek.loginWithPhone()`
and then call `gojek.generateCustomerToken()`

**Comment by adhikasp** [comment]
Cool, it's working now. Thanks a lot! :tada:
