### ISSUE TITLE
Bad request result

### ISSUE THREAD

**Issue by L200150097** [mychaelgo/gojek#9]
Why my result always bad result?
this in my script curl php version
![image](https://user-images.githubusercontent.com/31822581/33802358-16f169ce-dda8-11e7-8701-73dc35a18342.png)
and this result
![image](https://user-images.githubusercontent.com/31822581/33802362-399bb0c4-dda8-11e7-978f-404c3a08a0e4.png)
thanks.

**Comment by mychaelgo** [comment]
can you try again?
